name: Pull Request

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
      - name: Run tests
        run: pnpm test
      - name: Lint
        run: pnpm lint

  dependabot:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'aeria-org/create-aeria-app'

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: npm
      - name: Approve a PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

